version: "3.8"

services:

  metabase_ui:
    image: metabase/metabase:v0.52.4
    container_name: metapocket_ui
    ports:
      - "3080:3000"
    volumes:
      - type: bind
        source: ./metabase_data
        target: /metabase_data
      - type: bind
        source: ./pb_data
        target: /pb_shared_data
    environment:
      - MB_DB_FILE=/metabase_data/metabase.db
    restart: unless-stopped
    networks:
      - metanet
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  pocketbase:
    image: alpine
    container_name: metapocket_pb
    working_dir: /data
    volumes:
      - type: bind
        source: ./pb_data
        target: /data
    entrypoint:
      - sh
      - -c
      - |
        rm -f pocketbase.zip pocketbase && \
        wget -q -O pocketbase.zip https://github.com/pocketbase/pocketbase/releases/download/v0.25.0/pocketbase_0.25.0_linux_amd64.zip && \
        unzip -o pocketbase.zip && \
        ./pocketbase serve --dir /data --http 0.0.0.0:8090
    ports:
      - "3081:8090"
    restart: unless-stopped
    networks:
      - metanet

networks:
  metanet:
    driver: bridge
