version: '3'

services:

  metabase_ui:
    image: metabase/metabase:v0.52.4
    container_name: metapocket_ui
    ports:
      - 3080:3000
    volumes:
      - metapocket_data:/pb_data
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1512m
    restart: unless-stopped
    
    #network
    networks:
      - metabase_net

    # helth
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  metabase_server_<client>:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metapocket_server_<client>
    ports:
      - 3081:8090
    environment:
      - DATA_DIR=/pb_data_<client>
    volumes:
      - metapocket_data:${DATA_DIR}
    restart: unless-stopped
    
    #network
    networks:
      - metabase_net

volumes:
  metapocket_data:
    driver: local

networks:
  metabase_net:
    external: true