version: '3'

services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metapocket_server
    ports:
      - 3081:8090
    environment:
      - DATA_DIR=/pb_data
    volumes:
      - metapocket_data:/pb_data
    restart: unless-stopped
    #network
    networks:
      metabase_net:
        ipv4_address: 192.168.2.150
    dns:
      - 192.168.2.2

  metabase:
    image: metabase/metabase:v0.52.4
    container_name: metapocket_ui
    ports:
      - 3080:3000
    volumes:
      - metapocket_data:/pb_data
    environment:
      - JAVA_OPTS=-Xms512m -Xmx1512m
    restart: unless-stopped
    #network
    networks:
      metabase_net:
        ipv4_address: 192.168.2.151
    dns:
      - 192.168.2.2

    # helth
    healthcheck:
      test: curl --fail -I http://localhost:3000/api/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

volumes:
  metapocket_data:
    driver: local

networks:
  metabase_net:
    external: true
